spring.application.name=RSLFrancoBot
app.discord.token=

# Seed Generation API (external)
app.seed.api.domain=http://localhost:8081
app.seed.api.timeout.seconds=30

app.version=@project.version@
app.name=@project.name@