spring.application.name=RSLFrancoBot

# Discord Configuration (from environment)
app.discord.token=${DISCORD_TOKEN}

# Configuration Python Script RSL
app.python.command=python3
app.python.script.dir=/app/plando-random-settings
app.python.script.name=RandomSettingsGenerator.py
app.python.weights.rsl=weights/rsl_season7.json
app.python.weights.pot=weights/rsl_pot.json
app.python.weights.beginner=weights/rsl_season7_beginner.json

# Configuration API RSL Settings
app.rsl.api.base-url=https://prs-api.rawz06.fr/generate

# Configuration OoT Randomizer API (from environment)
app.randomizer.api.url=https://ootrandomizer.com/api/v2/seed/create
app.randomizer.api.key=${RANDOMIZER_API_KEY}
app.randomizer.api.version.rsl=devRSL_8.2.52-132
app.randomizer.api.version.rsl_s8=devrreal_9.0.2-17
app.randomizer.api.version.s8=8.3.0
app.randomizer.api.version.s9=9.0.0
app.randomizer.api.version.franco=devrreal_9.0.2-17
app.randomizer.api.version.tot=9.0.0
app.randomizer.api.version.enemySalad=devEnemyShuffle_9.0.2-24
app.randomizer.api.version.allsanity=devEnemyShuffle_9.0.2-24
app.randomizer.api.version.salad=devrreal_9.0.2-17
app.randomizer.api.version.mixed=devFenhl_9.0.42-2
app.randomizer.api.mode=http

# Logging configuration for production
logging.level.root=INFO
logging.level.fr.rawz06.rslfrancobot=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
