package fr.rawz06.rslfrancobot.api.repositories;

import com.fasterxml.jackson.databind.ObjectMapper;
import fr.rawz06.rslfrancobot.engine.domain.entities.Preset;
import fr.rawz06.rslfrancobot.engine.domain.ports.PresetRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Repository;
import org.yaml.snakeyaml.Yaml;

import java.io.InputStream;
import java.util.*;

/**
 * Implementation of preset repository.
 * Loads presets from YAML and JSON files in resources/data.
 */
@Repository
public class YamlPresetRepository implements PresetRepository {

    private static final Logger logger = LoggerFactory.getLogger(YamlPresetRepository.class);
    private final Map<String, Preset> presets = new HashMap<>();
    private final ObjectMapper objectMapper;

    public YamlPresetRepository(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
        loadPresets();
    }

    private void loadPresets() {
        try {
            loadFrancoPreset();
            loadRSLPreset();
            loadPoTPreset();
            loadBeginnerPreset();
            loadS8Preset();
            loadS9Preset();
            loadAllsanityPreset();
            loadSaladPreset();
            loadTotPreset();
            loadMixedPreset();
            logger.info("Presets loaded successfully: {}", presets.keySet());
        } catch (Exception e) {
            logger.error("Error loading presets", e);
        }
    }

    private void loadFrancoPreset() throws Exception {
        // Load base JSON file
        Map<String, Object> baseSettings = loadJsonFile("data/franco.json");

        // Load options from YAML
        List<Preset.PresetOption> options = loadFrancoOptionsFromYaml();

        Preset francoPreset = new Preset("franco", baseSettings, options);
        presets.put("franco", francoPreset);
    }

    private void loadRSLPreset() {
        // For RSL: no base settings, everything is generated by Python script
        // The script uses weights/rsl_season7.json
        try {
            Preset rslPreset = new Preset("rsl", Map.of(), List.of());
            presets.put("rsl", rslPreset);
        } catch (Exception e) {
            logger.error("Error loading RSL preset", e);
        }
    }

    private void loadPoTPreset() {
        // For PoT: no base settings, everything is generated by Python script
        // The script uses weights/rsl_pot.json
        try {
            Preset potPreset = new Preset("pot", Map.of(), List.of());
            presets.put("pot", potPreset);
        } catch (Exception e) {
            logger.error("Error loading PoT preset", e);
        }
    }

    private void loadBeginnerPreset() {
        // For Beginner: no base settings, everything is generated by Python script
        // The script uses weights/rsl_season7_beginner.json
        try {
            Preset beginnerPreset = new Preset("beginner", Map.of(), List.of());
            presets.put("beginner", beginnerPreset);
        } catch (Exception e) {
            logger.error("Error loading Beginner preset", e);
        }
    }

    private void loadS8Preset() {
        // For S8: fixed settings from s8.json, no user options
        try {
            Map<String, Object> baseSettings = loadJsonFile("data/s8.json");
            Preset s8Preset = new Preset("s8", baseSettings, List.of());
            presets.put("s8", s8Preset);
        } catch (Exception e) {
            logger.error("Error loading S8 preset", e);
        }
    }

    private void loadS9Preset() {
        // For S9: fixed settings from s9.json, no user options
        try {
            Map<String, Object> baseSettings = loadJsonFile("data/s9.json");
            Preset s9Preset = new Preset("s9", baseSettings, List.of());
            presets.put("s9", s9Preset);
        } catch (Exception e) {
            logger.error("Error loading S9 preset", e);
        }
    }

    private void loadTotPreset() {
        // For Tot: fixed settings from tot.json, no user options
        try {
            Map<String, Object> baseSettings = loadJsonFile("data/tot.json");
            Preset s9Preset = new Preset("tot", baseSettings, List.of());
            presets.put("tot", s9Preset);
        } catch (Exception e) {
            logger.error("Error loading Tot preset", e);
        }
    }

    private void loadMixedPreset() {
        // For Mixed: fixed settings from mixed.json, no user options
        try {
            Map<String, Object> baseSettings = loadJsonFile("data/mixed.json");
            Preset mixedPreset = new Preset("mixed", baseSettings, List.of());
            presets.put("mixed", mixedPreset);
        } catch (Exception e) {
            logger.error("Error loading Mixed preset", e);
        }
    }

    private void loadSaladPreset() {
        // For Salad: fixed settings from salad.json, no user options
        try {
            Map<String, Object> baseSettings = loadJsonFile("data/salad.json");
            Preset s9Preset = new Preset("salad", baseSettings, List.of());
            presets.put("salad", s9Preset);
        } catch (Exception e) {
            logger.error("Error loading Salad preset", e);
        }
    }

    private void loadAllsanityPreset() {
        // For Allsanity: fixed settings from allsanity.json, no user options
        try {
            Map<String, Object> baseSettings = loadJsonFile("data/allsanity.json");
            Preset allsanityPreset = new Preset("allsanity", baseSettings, List.of());
            presets.put("allsanity", allsanityPreset);
        } catch (Exception e) {
            logger.error("Error loading Allsanity preset", e);
        }
    }

    @SuppressWarnings("unchecked")
    private List<Preset.PresetOption> loadFrancoOptionsFromYaml() throws Exception {
        Yaml yaml = new Yaml();
        List<Preset.PresetOption> options = new ArrayList<>();

        try (InputStream inputStream = new ClassPathResource("data/franco.yaml").getInputStream()) {
            Map<String, Map<String, Object>> yamlData = yaml.load(inputStream);

            for (Map.Entry<String, Map<String, Object>> entry : yamlData.entrySet()) {
                String optionId = entry.getKey();
                Map<String, Object> optionData = entry.getValue();

                String label = (String) optionData.get("label");
                String description = (String) optionData.get("description");
                Map<String, Object> settingsToApply = (Map<String, Object>) optionData.get("settings");

                // Handle incompatibilities
                List<String> incompatibleWith = detectIncompatibilities(optionId);

                Preset.PresetOption option = new Preset.PresetOption(
                        optionId,
                        label,
                        description,
                        settingsToApply,
                        incompatibleWith
                );

                options.add(option);
            }
        }

        return options;
    }

    /**
     * Detects incompatibilities between options.
     * Based on legacy SettingParser logic.
     */
    private List<String> detectIncompatibilities(String optionId) {
        // List of known incompatibilities
        Map<String, List<String>> incompatibilitiesMap = Map.ofEntries(
                Map.entry("keysy", List.of("keysanity_all", "keyring_all", "keyring_regional")),
                Map.entry("keysanity_all", List.of("keysy", "keyring_all", "keyring_regional")),
                Map.entry("keyring_all", List.of("keysy", "keysanity_all", "keyring_regional")),
                Map.entry("keyring_regional", List.of("keysy", "keysanity_all", "keyring_all")),
                Map.entry("token_dj", List.of("token_ow", "token_all")),
                Map.entry("token_ow", List.of("token_dj", "token_all")),
                Map.entry("token_all", List.of("token_dj", "token_ow")),
                Map.entry("songsanity", List.of("songsanity_dungeon")),
                Map.entry("songsanity_dungeon", List.of("songsanity")),
                Map.entry("dungeon_er", List.of("dungeon_er_mixed")),
                Map.entry("dungeon_er_mixed", List.of("dungeon_er")),
                Map.entry("boss_souls", List.of("regional_souls", "souls")),
                Map.entry("regional_souls", List.of("boss_souls", "souls")),
                Map.entry("souls", List.of("boss_souls", "regional_souls")),
                Map.entry("minimal", List.of("scarce")),
                Map.entry("scarce", List.of("minimal")),
                // All bridge options are mutually incompatible
                Map.entry("bridge_6_med", List.of("bridge_4_med_bgk_6_med", "bridge_4_med_bgk_6_dj", "bridge_5_med_bgk_6_med", "bridge_5_med_bgk_6_dj", "bridge_1_stone", "bridge_2_stones", "bridge_3_stones", "bridge_vanilla", "bridge_5_dj", "bridge_6_dj", "bridge_7_dj", "bridge_8_dj", "bridge_9_dj", "precompleted_1", "precompleted_2", "precompleted_3")),
                Map.entry("bridge_4_med_bgk_6_med", List.of("bridge_6_med", "bridge_4_med_bgk_6_dj", "bridge_5_med_bgk_6_med", "bridge_5_med_bgk_6_dj", "bridge_1_stone", "bridge_2_stones", "bridge_3_stones", "bridge_vanilla", "bridge_5_dj", "bridge_6_dj", "bridge_7_dj", "bridge_8_dj", "bridge_9_dj", "precompleted_1", "precompleted_2", "precompleted_3")),
                Map.entry("bridge_4_med_bgk_6_dj", List.of("bridge_6_med", "bridge_4_med_bgk_6_med", "bridge_5_med_bgk_6_med", "bridge_5_med_bgk_6_dj", "bridge_1_stone", "bridge_2_stones", "bridge_3_stones", "bridge_vanilla", "bridge_5_dj", "bridge_6_dj", "bridge_7_dj", "bridge_8_dj", "bridge_9_dj", "precompleted_1", "precompleted_2", "precompleted_3")),
                Map.entry("bridge_5_med_bgk_6_med", List.of("bridge_6_med", "bridge_4_med_bgk_6_med", "bridge_4_med_bgk_6_dj", "bridge_5_med_bgk_6_dj", "bridge_1_stone", "bridge_2_stones", "bridge_3_stones", "bridge_vanilla", "bridge_5_dj", "bridge_6_dj", "bridge_7_dj", "bridge_8_dj", "bridge_9_dj", "precompleted_1", "precompleted_2", "precompleted_3")),
                Map.entry("bridge_5_med_bgk_6_dj", List.of("bridge_6_med", "bridge_4_med_bgk_6_med", "bridge_4_med_bgk_6_dj", "bridge_5_med_bgk_6_med", "bridge_1_stone", "bridge_2_stones", "bridge_3_stones", "bridge_vanilla", "bridge_5_dj", "bridge_6_dj", "bridge_7_dj", "bridge_8_dj", "bridge_9_dj", "precompleted_1", "precompleted_2", "precompleted_3")),
                Map.entry("bridge_1_stone", List.of("bridge_6_med", "bridge_4_med_bgk_6_med", "bridge_4_med_bgk_6_dj", "bridge_5_med_bgk_6_med", "bridge_5_med_bgk_6_dj", "bridge_2_stones", "bridge_3_stones", "bridge_vanilla", "bridge_5_dj", "bridge_6_dj", "bridge_7_dj", "bridge_8_dj", "bridge_9_dj", "precompleted_1", "precompleted_2", "precompleted_3")),
                Map.entry("bridge_2_stones", List.of("bridge_6_med", "bridge_4_med_bgk_6_med", "bridge_4_med_bgk_6_dj", "bridge_5_med_bgk_6_med", "bridge_5_med_bgk_6_dj", "bridge_1_stone", "bridge_3_stones", "bridge_vanilla", "bridge_5_dj", "bridge_6_dj", "bridge_7_dj", "bridge_8_dj", "bridge_9_dj", "precompleted_1", "precompleted_2", "precompleted_3")),
                Map.entry("bridge_3_stones", List.of("bridge_6_med", "bridge_4_med_bgk_6_med", "bridge_4_med_bgk_6_dj", "bridge_5_med_bgk_6_med", "bridge_5_med_bgk_6_dj", "bridge_1_stone", "bridge_2_stones", "bridge_vanilla", "bridge_5_dj", "bridge_6_dj", "bridge_7_dj", "bridge_8_dj", "bridge_9_dj", "precompleted_1", "precompleted_2", "precompleted_3")),
                Map.entry("bridge_vanilla", List.of("bridge_6_med", "bridge_4_med_bgk_6_med", "bridge_4_med_bgk_6_dj", "bridge_5_med_bgk_6_med", "bridge_5_med_bgk_6_dj", "bridge_1_stone", "bridge_2_stones", "bridge_3_stones", "bridge_5_dj", "bridge_6_dj", "bridge_7_dj", "bridge_8_dj", "bridge_9_dj", "precompleted_1", "precompleted_2", "precompleted_3")),
                Map.entry("bridge_5_dj", List.of("bridge_6_med", "bridge_4_med_bgk_6_med", "bridge_4_med_bgk_6_dj", "bridge_5_med_bgk_6_med", "bridge_5_med_bgk_6_dj", "bridge_1_stone", "bridge_2_stones", "bridge_3_stones", "bridge_vanilla", "bridge_6_dj", "bridge_7_dj", "bridge_8_dj", "bridge_9_dj", "precompleted_1", "precompleted_2", "precompleted_3")),
                Map.entry("bridge_6_dj", List.of("bridge_6_med", "bridge_4_med_bgk_6_med", "bridge_4_med_bgk_6_dj", "bridge_5_med_bgk_6_med", "bridge_5_med_bgk_6_dj", "bridge_1_stone", "bridge_2_stones", "bridge_3_stones", "bridge_vanilla", "bridge_5_dj", "bridge_7_dj", "bridge_8_dj", "bridge_9_dj", "precompleted_1", "precompleted_2", "precompleted_3")),
                Map.entry("bridge_7_dj", List.of("bridge_6_med", "bridge_4_med_bgk_6_med", "bridge_4_med_bgk_6_dj", "bridge_5_med_bgk_6_med", "bridge_5_med_bgk_6_dj", "bridge_1_stone", "bridge_2_stones", "bridge_3_stones", "bridge_vanilla", "bridge_5_dj", "bridge_6_dj", "bridge_8_dj", "bridge_9_dj", "precompleted_1", "precompleted_2", "precompleted_3")),
                Map.entry("bridge_8_dj", List.of("bridge_6_med", "bridge_4_med_bgk_6_med", "bridge_4_med_bgk_6_dj", "bridge_5_med_bgk_6_med", "bridge_5_med_bgk_6_dj", "bridge_1_stone", "bridge_2_stones", "bridge_3_stones", "bridge_vanilla", "bridge_5_dj", "bridge_6_dj", "bridge_7_dj", "bridge_9_dj", "precompleted_1", "precompleted_2", "precompleted_3")),
                Map.entry("bridge_9_dj", List.of("bridge_6_med", "bridge_4_med_bgk_6_med", "bridge_4_med_bgk_6_dj", "bridge_5_med_bgk_6_med", "bridge_5_med_bgk_6_dj", "bridge_1_stone", "bridge_2_stones", "bridge_3_stones", "bridge_vanilla", "bridge_5_dj", "bridge_6_dj", "bridge_7_dj", "bridge_8_dj", "precompleted_1", "precompleted_2", "precompleted_3")),
                Map.entry("precompleted_1", List.of("precompleted_2", "precompleted_3", "bridge_6_med", "bridge_4_med_bgk_6_med", "bridge_4_med_bgk_6_dj", "bridge_5_med_bgk_6_med", "bridge_5_med_bgk_6_dj", "bridge_1_stone", "bridge_2_stones", "bridge_3_stones", "bridge_vanilla", "bridge_5_dj", "bridge_6_dj", "bridge_7_dj", "bridge_8_dj", "bridge_9_dj")),
                Map.entry("precompleted_2", List.of("precompleted_1", "precompleted_3", "bridge_6_med", "bridge_4_med_bgk_6_med", "bridge_4_med_bgk_6_dj", "bridge_5_med_bgk_6_med", "bridge_5_med_bgk_6_dj", "bridge_1_stone", "bridge_2_stones", "bridge_3_stones", "bridge_vanilla", "bridge_5_dj", "bridge_6_dj", "bridge_7_dj", "bridge_8_dj", "bridge_9_dj")),
                Map.entry("precompleted_3", List.of("precompleted_1", "precompleted_2", "bridge_6_med", "bridge_4_med_bgk_6_med", "bridge_4_med_bgk_6_dj", "bridge_5_med_bgk_6_med", "bridge_5_med_bgk_6_dj", "bridge_1_stone", "bridge_2_stones", "bridge_3_stones", "bridge_vanilla", "bridge_5_dj", "bridge_6_dj", "bridge_7_dj", "bridge_8_dj", "bridge_9_dj"))
        );

        return incompatibilitiesMap.getOrDefault(optionId, List.of());
    }

    @SuppressWarnings("unchecked")
    private Map<String, Object> loadJsonFile(String path) throws Exception {
        try (InputStream inputStream = new ClassPathResource(path).getInputStream()) {
            return objectMapper.readValue(inputStream, Map.class);
        }
    }

    @Override
    public Optional<Preset> getPreset(String name) {
        return Optional.ofNullable(presets.get(name.toLowerCase()));
    }

    @Override
    public boolean presetExists(String name) {
        return presets.containsKey(name.toLowerCase());
    }
}
